BUNDLE_NAME = hidesuggestionsprefs
hidesuggestionsprefs_FILES = HSRootListController.m
hidesuggestionsprefs_FRAMEWORKS = UIKit
hidesuggestionsprefs_PRIVATE_FRAMEWORKS = Preferences
hidesuggestionsprefs_INSTALL_PATH = /Library/PreferenceBundles
hidesuggestionsprefs_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk